name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs==1.5.2
      - run: pip install mkdocs-material==9.4.1
      - run: pip install pillow cairosvg
      - run: pip install mkdocs-awesome-pages-plugin
      - run: pip install mkdocs-blogging-plugin
      - run: pip install mkdocs-rss-plugin
      - run: mkdocs gh-deploy --force
